export const MODES = {
  M: {
    name: "M Console",
    accentText: "text-red-400",
    accentSoftText: "text-red-300",
    accentBg: "bg-red-600",
    accentBgSoft: "bg-red-950/35",
    accentBorder: "border-red-600",
    glow: "rgba(239, 68, 68, 0.24)",
    grid: "rgba(239, 68, 68, 0.17)",
    wallGrid: "rgba(255, 72, 72, 0.20)",
    floorGrid: "rgba(255, 96, 96, 0.62)",
    sceneTuning: {
      wallGrid: 2.35,
      floorGrid: 1.6,
      spotGlow: 0.5,
    },
    screenFrame: {
      left: 22.0,
      top: 22.3,
      width: 42.5,
      height: 55.7,
      radius: 8.7,
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0.7,
    },
    firmware: "M Ultimate Pack v1.3",
    quickIcon: "⚡",
  },
  Z: {
    name: "Z Console",
    accentText: "text-emerald-400",
    accentSoftText: "text-emerald-300",
    accentBg: "bg-emerald-600",
    accentBgSoft: "bg-emerald-950/35",
    accentBorder: "border-emerald-500",
    glow: "rgba(16, 185, 129, 0.24)",
    grid: "rgba(16, 185, 129, 0.17)",
    wallGrid: "rgba(38, 255, 167, 0.18)",
    floorGrid: "rgba(52, 255, 176, 0.40)",
    sceneTuning: {
      wallGrid: 0.75,
      floorGrid: 1.3,
      spotGlow: 0.5,
    },
    screenFrame: {
      left: 21.6,
      top: 22.0,
      width: 41.1,
      height: 51.7,
      radius: 11.3,
      rotateX: 0,
      rotateY: 0,
      rotateZ: 1.1,
    },
    firmware: "Z Retro Pack v2.1",
    quickIcon: "⚔",
  },
};

export const TRANSLATIONS = {
  ru: {
    settings: "Настройки",
    language: "Язык",
    updateProgram: "Обновить программу",
    checkingUpdate: "Проверка обновления...",
    installingUpdate: "Установка обновления...",
    updateAvailable: "На сервере доступно обновление",
    upToDate: "Программа обновлена",
    updateConfirmTitle: "Доступна версия {version}",
    updateConfirmMessage: "Текущая версия: {current}. Новая версия: {version}. Скачать, заменить приложение и перезапустить?",
    updateNow: "Обновить сейчас",
    updateCheckFailed: "Не удалось проверить обновление. Проверьте интернет или откройте GitHub Repository вручную.",
    githubRepository: "🌐 GitHub Repository",
    sayThanks: "❤️ Say Thanks",
    ok: "OK",
    close: "Закрыть",
    buildOptions: "Параметры сборки",
    stockFirmwareMode: "Стоковая прошивка",
    dualBootHint: "M/Z: собрать Stock + Retro-Go в режиме dual boot",
    retroGoOnlyHint: "NONE: собрать только Retro-Go без stock и dual boot",
    hardwareModel: "Железо для Retro-Go",
    defaultSpiCapacity: "SPI: {size} MB по выбранному профилю. Прочитайте консоль для определения реального размера.",
    detectedSpiCapacity: "SPI: {size} MB, определено по подключённой консоли.",
    selectedSpiCapacity: "SPI: выбрано {size} MB для офлайн-сборки.",
    spiCapacityNotSelected: "SPI: размер будет запрошен после нажатия «Собрать прошивку».",
    selectedSpiTooSmall: "Выбрано {selected} MB, но сборке требуется примерно {required} MB. Нажмите Build и выберите больший размер SPI.",
    selectSpiCapacity: "Выберите размер внешней памяти",
    selectSpiCapacityHint: "Консоль не прочитана. Выберите фактически установленную SPI flash для корректной сборки.",
    stockCapacity: "STOCK",
    downloadImages: "Скачать картинки",
    downloadingImages: "Загрузка картинок...",
    downloadingMenuCovers: "Загрузка обложек меню для ROM",
    downloadImagesHint: "Скачайте обложки перед Build, иначе Retro-Go покажет игры обычным списком",
    noPreviewSource: "Для загруженных ROM нет источника превью",
    buildFirmware: "Собрать прошивку",
    firmwareBuilt: "Прошивка собрана",
    firmwareBuiltCanFlash: "Можно прошивать",
    openFirmwareFolder: "Открыть папку с прошивкой",
    openFirmwareFolderHint: "Файлы для ручной прошивки через Raspberry Pi или другой программатор",
    buildingFirmware: "Сборка...",
    packRomsImages: "Упаковать ROM и картинки",
    retroGoStart: "Запуск Retro-Go: нажмите LEFT + GAME в стоковой прошивке.",
    retroGoOnlyStart: "Retro-Go запускается напрямую при включении.",
    loadRomsToBuild: "Загрузите ROM для подготовки прошивки",
    deviceNotIdentified: "Консоль не определена",
    protectedDevice: "Защищённая консоль недоступна для записи",
    waitImageDownload: "Дождитесь завершения загрузки картинок",
    importStockFiles: "Импортируйте нужные StockFirmware файлы",
    buildTooLarge: "Отключено: превышение SPI больше 30%",
    packingBundle: "Упаковка ROM, превью и manifest",
    stockBackupRequired: "Нужна stock прошивка",
    stockFirmwareDropHint: "Перетащите сюда оригинальные Bank1 и SPI файлы или выберите их вручную.",
    stockFirmwareRequiredMessage: "Для dual boot сборки нужны оригинальные {firmware} stock-файлы. После проверки они будут сохранены в StockFirmware.",
    mcuBank1: "MCU Bank1",
    spiFlash: "SPI Flash",
    selectBackup: "Выбрать backup",
    buildFailed: "Ошибка сборки",
    loadedGames: "Загруженные игры",
    emulatorBuilder: "Эмуляторы",
    warning: "Предупреждения",
    liveLog: "Лог",
    flashDevice: "Прошить консоль",
    backupManager: "Менеджер backup",
    deviceStatus: "Статус консоли",
    programmer: "Программатор",
    deviceUid: "Device UID",
    voltage: "Напряжение",
    detectedFirmware: "Определённая прошивка",
    externalFlash: "Внешняя flash",
    protection: "Защита",
    gameStorage: "Хранилище игр",
    readingDeviceInfo: "Чтение информации...",
    readDeviceInfo: "Прочитать консоль",
    deviceReadFailedHint: "Устройство не определилось. Проверьте подключение ST-LINK и питание консоли, нажмите кнопку включения на консоли и повторите Read Device Info.",
    noWarnings: "Нет предупреждений",
    systemOk: "Проверка системы пройдена",
    languageUpdate: "Язык и обновление программы",
    programUpdate: "Обновление программы",
    probeFrequency: "Частота ST-LINK",
    probeFrequencyHint: "Старт с {khz} kHz, при ошибках чтения частота снижается автоматически",
    advancedFlasher: "Advanced Flasher",
    advancedFlasherHint: "Показать ручной backup и ручную запись прошивок",
    on: "Вкл",
    off: "Выкл",
    memoryUsage: "Использование памяти",
    builtSpiImage: "Собранный SPI образ",
    overflow: "Переполнение",
    used: "Использовано",
    emulatorRomsImage: "ROM / картинки эмуляторов",
    builtExtflash: "Собранный EXTFLASH",
    realSize: "Реальный размер",
    runBuildFirmware: "Запустите Build Firmware",
    readDeviceInfoMemory: "Прочитайте консоль, чтобы показать SPI и память.",
    sdCard: "SD карта",
    backupShort: "BACKUP",
    fullBackupReady: "Backup сохранён под UID консоли",
    readOrSelectBackup: "Сохраняет прошивку под UID консоли",
    buildEmulator: "Собрать эмулятор",
    configureEmulatorCores: "Настроить ядра эмуляторов",
    openEmulatorConfig: "Открыть настройку эмуляторов",
    recoveryRestoreMode: "Режим восстановления",
    writeFirmwareToDevice: "Записать прошивку в консоль",
    nameAZ: "Имя A-Z",
    nameZA: "Имя Z-A",
    sizeUp: "Размер ↑",
    sizeDown: "Размер ↓",
    importImages: "Импорт картинок",
    scanFolder: "Сканировать папку",
    clearRoms: "Очистить ROM",
    noGamesLoaded: "Игры не загружены",
    openRomFolder: "Откройте папку ROM для выбранного эмулятора",
    addRomsAny: "Добавьте ROM для любого эмулятора",
    unknownEmulator: "Неизвестный эмулятор",
    screenshotLoaded: "Скриншот загружен",
    downloadingImage: "Загрузка картинки...",
    noScreenshotFound: "Скриншот не найден",
    noImage: "Нет картинки",
    setImage: "Выбрать картинку",
    setImageManual: "Выбрать картинку вручную",
    removeFromList: "Удалить из списка",
    clear: "Очистить",
    firmwareRecovery: "Восстановление прошивки",
    firmwareRecoveryTitle: "Консоль перестала включаться или прошивка повреждена?",
    firmwareRecoveryText: "Процессор и UID читаются, но stock firmware не определяется. GW Studio попробует найти backup для UID {uid} и подготовить восстановление во Flash Device. Если backup не найден, нужно будет выбрать Bank1 и SPI файлы вручную.",
    yesRecover: "Да, восстановить",
    findBackupOrManual: "Найти backup или выбрать файлы вручную",
    no: "Нет",
    leaveBlocked: "Оставить операции заблокированными",
    restoreOriginalFirmware: "Восстановить оригинальную прошивку",
    selectHardwareModel: "Выберите реальную модель консоли",
    restoreOriginalHint: "M Hardware нужно восстанавливать stock-профилем M, Z Hardware — stock-профилем Z. Не используйте это для превращения одной модели консоли в другую.",
    marioHardware: "M Hardware",
    zeldaHardware: "Z Hardware",
    cancel: "Отмена",
    msxBiosRequired: "Нужен MSX BIOS",
    msxBiosHint: "В сборке есть MSX игры. Перетащите сюда все MSX BIOS файлы, программа сохранит их рядом с exe в папку msx_bios и автоматически повторит Build Firmware.",
    colecoBiosRequired: "Нужен ColecoVision BIOS",
    colecoBiosHint: "В сборке есть ColecoVision игры. Перетащите файл coleco.rom вручную. Программа проверит размер 8192 байта и SHA-1, сохранит BIOS рядом с exe в папку coleco_bios и повторит Build Firmware.",
    missingBios: "Не хватает BIOS",
    checking: "Проверка...",
    autoFlash: "Прошить сборку",
    autoFlashConfirm: "Вы уверены? Будет произведена прошивка Bank1 + Bank2 + SPI.",
    flashBuildTitle: "Прошить сборку",
    flashBuildConfirm: "Вы уверены? Будет прошита текущая сборка: Bank1 + Bank2 + SPI.",
    flashBuildButton: "Прошить сборку",
    autoFlashRunning: "Прошивка сборки...",
    autoFlashDone: "Прошивка завершена",
    autoFlashDoneHint: "Готово: Bank1 + Bank2 + SPI записаны",
    writingBankSpi: "Запись Bank1 + Bank2 + SPI",
    buildFirmwareFirst: "Сначала соберите прошивку",
    firmwareBuiltReady: "Прошивка собрана, можно прошивать",
    flashStockForkSpi: "Записать stock Bank1 + Bank2 fork + SPI",
    flashRetroGoOnly: "Записать Retro-Go Bank1 + SPI",
    writingSingleFirmware: "Запись Retro-Go Bank1 + SPI",
    singleFirmwareFlashConfirm: "Будет записана single firmware для hardware {hardware}: {targets}. Stock firmware и dual boot будут удалены.",
    bank1Missing: "Не найден Bank1 dualboot firmware",
    bank2Missing: "Не найден Bank2 fork firmware",
    restoreDevice: "Восстановить прошивку",
    restoreDeviceConfirm: "Вы точно хотите восстановить прошивку из backup, который привязан к UID {uid}?",
    unbrickDevice: "Unbrick Device",
    unbrickRunning: "Unbrick Device...",
    restoreDeviceRunning: "Восстановление прошивки...",
    installRecoveryFiles: "Запись stock firmware / recovery файлов",
    restoreSavedBackup: "Восстановление из бэкапа по UID",
    installSelectedRecovery: "Записать выбранные stock Bank1 + SPI",
    selectRecoveryFirst: "Сначала выберите Bank1 и SPI recovery файлы",
    restoreMcuSpiBackup: "Восстановить MCU + SPI из бэкапа по UID",
    readOrSelectMcuSpi: "Сначала прочитайте консоль или выберите MCU + SPI backup",
    restoreOriginalRunning: "Restore Original...",
    chooseHardwareThenFlash: "Выберите M/Z Hardware, затем будет записан stock",
    advancedFlash: "Advanced Flash",
    bank1Firmware: "Bank1 Firmware",
    bank2Firmware: "Bank2 Firmware",
    spiFirmware: "SPI Firmware",
    selectBank1Firmware: "Выберите Bank1 firmware file",
    resolvedBank2Payload: "Найденный Bank2 payload",
    selectSpiFirmware: "Выберите SPI firmware file",
    writeBank1: "Write Bank1",
    writeBank2: "Write Bank2",
    writeSpiFlash: "Write SPI Flash",
    writeSelectedBank1: "Записать выбранный Bank1 firmware",
    writeBank2Payload: "Записать Bank2 payload в 0x08100000",
    writeSelectedSpi: "Записать выбранный SPI firmware",
    checkingSpiSectors: "Проверка изменённых SPI секторов...",
    prepareSpiFlash: "Подготовка SPI Flash",
    eraseSpiFlash: "Очистка SPI Flash",
    verifySpiFlash: "Проверка SPI Flash",
    writeSpiFlashProgress: "Запись SPI Flash",
    writeBank1Progress: "Запись Bank1",
    writeBank2Progress: "Запись Bank2",
    verifyingSpi: "Проверка записанной SPI flash...",
    erasingSpi: "Очистка внешней SPI flash...",
    writingFirmware: "Запись прошивки...",
    readingFromDevice: "Чтение из консоли",
    backup: "Backup",
    bank1Backup: "Bank1 Backup",
    bank2Backup: "Bank2 Backup",
    spiBackup: "SPI Backup",
    backupAppearsAfterSave: "Файл backup появится в /backups после сохранения",
    advancedBackupAppearsAfterSave: "Advanced backup появится после сохранения",
    lockedBankReadUnavailable: "LOCKED: чтение Bank недоступно",
    readBank1: "Read Bank1",
    readBank2: "Read Bank2",
    readSpiFlash: "Read SPI Flash",
    readingBank1: "Reading Bank1...",
    readingBank2: "Reading Bank2...",
    readingSpi: "Reading SPI...",
    readBank1Backup: "Прочитать Bank1 backup из консоли",
    readBank2Backup: "Прочитать Bank2 backup из консоли",
    readSpiBackup: "Прочитать SPI flash backup из консоли",
    showInExplorer: "Показать в Explorer",
    runningAutoBackup: "Running Auto Backup...",
    autoBackupFinished: "Auto backup завершён",
    autoBackup: "Auto Backup",
    readSpiLocked: "Прочитать SPI backup с locked консоли",
    readFullBackup: "Сохраняет Bank1 + Bank2 + SPI backup под UID консоли",
    advancedBackup: "Advanced Backup",
  },
  en: {
    settings: "Settings",
    language: "Language",
    updateProgram: "Update program",
    checkingUpdate: "Checking update...",
    installingUpdate: "Installing update...",
    updateAvailable: "Update available on server",
    upToDate: "Program is up to date",
    updateConfirmTitle: "Version {version} is available",
    updateConfirmMessage: "Current version: {current}. New version: {version}. Download, replace the application and restart?",
    updateNow: "Update now",
    updateCheckFailed: "Failed to check for updates. Check the internet connection or open GitHub Repository manually.",
    githubRepository: "🌐 GitHub Repository",
    sayThanks: "❤️ Say Thanks",
    ok: "OK",
    close: "Close",
    buildOptions: "Build options",
    stockFirmwareMode: "Stock firmware",
    dualBootHint: "M/Z: build Stock + Retro-Go in dual boot mode",
    retroGoOnlyHint: "NONE: build Retro-Go only, without stock or dual boot",
    hardwareModel: "Retro-Go hardware",
    defaultSpiCapacity: "SPI: {size} MB from the selected profile. Read the device to detect the actual size.",
    detectedSpiCapacity: "SPI: {size} MB detected from the connected device.",
    selectedSpiCapacity: "SPI: {size} MB selected for offline build.",
    spiCapacityNotSelected: "SPI: size will be requested after pressing Build firmware.",
    selectedSpiTooSmall: "Selected {selected} MB, but the build needs about {required} MB. Press Build and select a larger SPI size.",
    selectSpiCapacity: "Select external memory size",
    selectSpiCapacityHint: "The device has not been read. Select the actual installed SPI flash size for a correct build.",
    stockCapacity: "STOCK",
    downloadImages: "Download images",
    downloadingImages: "Downloading...",
    downloadingMenuCovers: "Downloading menu covers for loaded ROMs",
    downloadImagesHint: "Download covers before Build, otherwise Retro-Go will use a simple list menu",
    noPreviewSource: "No supported preview source for loaded ROMs",
    buildFirmware: "Build firmware",
    firmwareBuilt: "Firmware built",
    firmwareBuiltCanFlash: "Ready to flash",
    openFirmwareFolder: "Open firmware folder",
    openFirmwareFolderHint: "Files for manual flashing with Raspberry Pi or another programmer",
    buildingFirmware: "Building...",
    packRomsImages: "Pack ROMs and images",
    retroGoStart: "Start Retro-Go: press LEFT + GAME in stock firmware.",
    retroGoOnlyStart: "Retro-Go starts directly at power-on.",
    loadRomsToBuild: "Load ROMs to prepare firmware build",
    deviceNotIdentified: "Device not identified",
    protectedDevice: "Protected device is not writable",
    waitImageDownload: "Wait for image download to finish",
    importStockFiles: "Import required StockFirmware files",
    buildTooLarge: "Disabled: exceeds SPI by more than 30%",
    packingBundle: "Packing ROMs, previews and manifest",
    stockBackupRequired: "Stock firmware required",
    stockFirmwareDropHint: "Drop original Bank1 and SPI files here, or select them manually.",
    stockFirmwareRequiredMessage: "Dual boot build needs original {firmware} stock files. After verification they will be saved in StockFirmware.",
    mcuBank1: "MCU Bank1",
    spiFlash: "SPI Flash",
    selectBackup: "Select backup",
    buildFailed: "Build failed",
    loadedGames: "Loaded games",
    emulatorBuilder: "Emulator builder",
    warning: "Warnings",
    liveLog: "Live log",
    flashDevice: "Flash device",
    backupManager: "Backup manager",
    deviceStatus: "Device status",
    programmer: "Programmer",
    deviceUid: "Device UID",
    voltage: "Voltage",
    detectedFirmware: "Detected firmware",
    externalFlash: "External flash",
    protection: "Protection",
    gameStorage: "Game storage",
    readingDeviceInfo: "Reading device info...",
    readDeviceInfo: "Read device info",
    deviceReadFailedHint: "Device was not identified. Check ST-LINK connection and console power, press the console power button, then repeat Read Device Info.",
    noWarnings: "No warnings",
    systemOk: "System check passed",
    languageUpdate: "Language and program update",
    programUpdate: "Program update",
    probeFrequency: "ST-LINK frequency",
    probeFrequencyHint: "Start at {khz} kHz, auto-fallback lower on read errors",
    advancedFlasher: "Advanced Flasher",
    advancedFlasherHint: "Show manual backup and firmware write controls",
    on: "On",
    off: "Off",
    memoryUsage: "Memory usage",
    builtSpiImage: "Built SPI image",
    overflow: "Overflow",
    used: "Used",
    emulatorRomsImage: "Emulator ROMs / images",
    builtExtflash: "Built EXTFLASH",
    realSize: "Real size",
    runBuildFirmware: "Run Build Firmware",
    readDeviceInfoMemory: "Read Device Info to populate installed SPI and memory usage.",
    sdCard: "SD card",
    backupShort: "BACKUP",
    fullBackupReady: "Backup saved under device UID",
    readOrSelectBackup: "Saves firmware under the device UID",
    buildEmulator: "Build emulator",
    configureEmulatorCores: "Configure emulator cores",
    openEmulatorConfig: "Open emulator configuration",
    recoveryRestoreMode: "Recovery restore mode",
    writeFirmwareToDevice: "Write firmware to device",
    nameAZ: "Name A-Z",
    nameZA: "Name Z-A",
    sizeUp: "Size ↑",
    sizeDown: "Size ↓",
    importImages: "Import images",
    scanFolder: "Scan folder",
    clearRoms: "Clear ROMs",
    noGamesLoaded: "No games loaded",
    openRomFolder: "Open ROM folder for selected emulator",
    addRomsAny: "Add ROMs for any emulator",
    unknownEmulator: "Unknown emulator",
    screenshotLoaded: "Screenshot loaded",
    downloadingImage: "Downloading image...",
    noScreenshotFound: "No screenshot found",
    noImage: "No image",
    setImage: "Set image",
    setImageManual: "Set image manually",
    removeFromList: "Remove from list",
    clear: "Clear",
    firmwareRecovery: "Firmware recovery",
    firmwareRecoveryTitle: "Console stopped booting or firmware is corrupted?",
    firmwareRecoveryText: "CPU and UID are readable, but stock firmware is not detected. GW Studio will try to find a backup for UID {uid} and prepare recovery in Flash Device. If no backup is found, select Bank1 and SPI files manually.",
    yesRecover: "Yes, recover",
    findBackupOrManual: "Find backup or select files manually",
    no: "No",
    leaveBlocked: "Leave operations blocked",
    restoreOriginalFirmware: "Restore Original Firmware",
    selectHardwareModel: "Select the real hardware model",
    restoreOriginalHint: "M Hardware must be restored with stock profile M, and Z Hardware with stock profile Z. Do not use this to convert one console model into another.",
    marioHardware: "M Hardware",
    zeldaHardware: "Z Hardware",
    cancel: "Cancel",
    msxBiosRequired: "MSX BIOS Required",
    msxBiosHint: "The build contains MSX games. Drop all MSX BIOS files here; the program will save them next to the exe in msx_bios and retry Build Firmware automatically.",
    colecoBiosRequired: "ColecoVision BIOS Required",
    colecoBiosHint: "The build contains ColecoVision games. Drop coleco.rom manually. The program will verify 8192 bytes and SHA-1, save the BIOS next to the exe in coleco_bios, and retry Build Firmware.",
    missingBios: "Missing BIOS",
    checking: "Checking...",
    autoFlash: "Flash build",
    autoFlashConfirm: "Are you sure? Bank1 + Bank2 + SPI will be flashed.",
    flashBuildTitle: "Flash build",
    flashBuildConfirm: "Are you sure? The current build will be flashed: Bank1 + Bank2 + SPI.",
    flashBuildButton: "Flash build",
    autoFlashRunning: "Flashing build...",
    autoFlashDone: "Flash completed",
    autoFlashDoneHint: "Done: Bank1 + Bank2 + SPI written",
    writingBankSpi: "Writing Bank1 + Bank2 + SPI",
    buildFirmwareFirst: "Build firmware first",
    firmwareBuiltReady: "Firmware is built, ready to flash",
    flashStockForkSpi: "Flash stock Bank1 + Bank2 fork + SPI",
    flashRetroGoOnly: "Flash Retro-Go Bank1 + SPI",
    writingSingleFirmware: "Writing Retro-Go Bank1 + SPI",
    singleFirmwareFlashConfirm: "Single firmware for {hardware} hardware will be flashed: {targets}. Stock firmware and dual boot will be removed.",
    bank1Missing: "Bank1 dualboot firmware is missing",
    bank2Missing: "Bank2 fork firmware is missing",
    restoreDevice: "Restore from UID backup",
    restoreDeviceConfirm: "Are you sure you want to restore firmware from the backup linked to UID {uid}?",
    unbrickDevice: "Unbrick Device",
    unbrickRunning: "Unbrick Device...",
    restoreDeviceRunning: "Restoring firmware...",
    installRecoveryFiles: "Install stock firmware / recovery files",
    restoreSavedBackup: "Restoring from UID backup",
    installSelectedRecovery: "Install selected stock Bank1 + SPI",
    selectRecoveryFirst: "Select Bank1 and SPI recovery files first",
    restoreMcuSpiBackup: "Restore MCU + SPI from UID backup",
    readOrSelectMcuSpi: "Read the device or select MCU + SPI backup first",
    restoreOriginalRunning: "Restore Original...",
    chooseHardwareThenFlash: "Choose M/Z Hardware, then flash stock",
    advancedFlash: "Advanced Flash",
    bank1Firmware: "Bank1 Firmware",
    bank2Firmware: "Bank2 Firmware",
    spiFirmware: "SPI Firmware",
    selectBank1Firmware: "Select Bank1 firmware file",
    resolvedBank2Payload: "Resolved Bank2 payload",
    selectSpiFirmware: "Select SPI firmware file",
    writeBank1: "Write Bank1",
    writeBank2: "Write Bank2",
    writeSpiFlash: "Write SPI Flash",
    writeSelectedBank1: "Write selected Bank1 firmware",
    writeBank2Payload: "Write Bank2 payload to 0x08100000",
    writeSelectedSpi: "Write selected SPI firmware",
    checkingSpiSectors: "Checking changed SPI sectors...",
    prepareSpiFlash: "Prepare SPI Flash",
    eraseSpiFlash: "Erase SPI Flash",
    verifySpiFlash: "Verify SPI Flash",
    writeSpiFlashProgress: "Write SPI Flash",
    writeBank1Progress: "Write Bank1",
    writeBank2Progress: "Write Bank2",
    verifyingSpi: "Verifying written SPI flash...",
    erasingSpi: "Erasing external SPI flash...",
    writingFirmware: "Writing firmware...",
    readingFromDevice: "Reading from device",
    backup: "Backup",
    bank1Backup: "Bank1 Backup",
    bank2Backup: "Bank2 Backup",
    spiBackup: "SPI Backup",
    backupAppearsAfterSave: "Backup file will appear in /backups after save",
    advancedBackupAppearsAfterSave: "Advanced backup file will appear after save",
    lockedBankReadUnavailable: "LOCKED: bank read unavailable",
    readBank1: "Read Bank1",
    readBank2: "Read Bank2",
    readSpiFlash: "Read SPI Flash",
    readingBank1: "Reading Bank1...",
    readingBank2: "Reading Bank2...",
    readingSpi: "Reading SPI...",
    readBank1Backup: "Read Bank1 backup from device",
    readBank2Backup: "Read Bank2 backup from device",
    readSpiBackup: "Read SPI flash backup from device",
    showInExplorer: "Show in Explorer",
    runningAutoBackup: "Running Auto Backup...",
    autoBackupFinished: "Auto backup finished",
    autoBackup: "Auto Backup",
    readSpiLocked: "Read SPI backup from locked device",
    readFullBackup: "Saves Bank1 + Bank2 + SPI backup under the device UID",
    advancedBackup: "Advanced Backup",
  },
  uk: {
    settings: "Налаштування",
    language: "Мова",
    updateProgram: "Оновити програму",
    checkingUpdate: "Перевірка оновлення...",
    installingUpdate: "Встановлення оновлення...",
    updateAvailable: "На сервері доступне оновлення",
    upToDate: "Програму оновлено",
    updateConfirmTitle: "Доступна версія {version}",
    updateConfirmMessage: "Поточна версія: {current}. Нова версія: {version}. Завантажити, замінити програму та перезапустити?",
    updateNow: "Оновити зараз",
    updateCheckFailed: "Не вдалося перевірити оновлення. Перевірте інтернет або відкрийте GitHub Repository вручну.",
    githubRepository: "🌐 GitHub Repository",
    sayThanks: "❤️ Say Thanks",
    ok: "OK",
    close: "Закрити",
    buildOptions: "Параметри збірки",
    stockFirmwareMode: "Стокова прошивка",
    dualBootHint: "M/Z: зібрати Stock + Retro-Go у режимі dual boot",
    retroGoOnlyHint: "NONE: зібрати лише Retro-Go без stock і dual boot",
    hardwareModel: "Залізо для Retro-Go",
    defaultSpiCapacity: "SPI: {size} MB за вибраним профілем. Прочитайте консоль для визначення реального розміру.",
    detectedSpiCapacity: "SPI: {size} MB, визначено за підключеною консоллю.",
    selectedSpiCapacity: "SPI: вибрано {size} MB для офлайн-збірки.",
    spiCapacityNotSelected: "SPI: розмір буде запитано після натискання «Зібрати прошивку».",
    selectedSpiTooSmall: "Вибрано {selected} MB, але збірці потрібно приблизно {required} MB. Натисніть Build і виберіть більший розмір SPI.",
    selectSpiCapacity: "Виберіть розмір зовнішньої пам'яті",
    selectSpiCapacityHint: "Консоль не прочитана. Виберіть фактично встановлену SPI flash для коректної збірки.",
    stockCapacity: "STOCK",
    downloadImages: "Завантажити картинки",
    downloadingImages: "Завантаження...",
    downloadingMenuCovers: "Завантаження обкладинок меню для ROM",
    downloadImagesHint: "Завантажте обкладинки перед Build, інакше Retro-Go покаже ігри звичайним списком",
    noPreviewSource: "Для завантажених ROM немає джерела превʼю",
    buildFirmware: "Зібрати прошивку",
    firmwareBuilt: "Прошивку зібрано",
    firmwareBuiltCanFlash: "Можна прошивати",
    openFirmwareFolder: "Відкрити папку з прошивкою",
    openFirmwareFolderHint: "Файли для ручної прошивки через Raspberry Pi або інший програматор",
    buildingFirmware: "Збірка...",
    packRomsImages: "Упакувати ROM і картинки",
    retroGoStart: "Запуск Retro-Go: натисніть LEFT + GAME у стоковій прошивці.",
    retroGoOnlyStart: "Retro-Go запускається одразу після ввімкнення.",
    loadRomsToBuild: "Завантажте ROM для підготовки прошивки",
    deviceNotIdentified: "Консоль не визначена",
    protectedDevice: "Захищена консоль недоступна для запису",
    waitImageDownload: "Дочекайтесь завершення завантаження картинок",
    importStockFiles: "Імпортуйте потрібні StockFirmware файли",
    buildTooLarge: "Вимкнено: перевищення SPI більше 30%",
    packingBundle: "Пакування ROM, превʼю та manifest",
    stockBackupRequired: "Потрібна stock прошивка",
    stockFirmwareDropHint: "Перетягніть сюди оригінальні Bank1 і SPI файли або виберіть їх вручну.",
    stockFirmwareRequiredMessage: "Для dual boot збірки потрібні оригінальні {firmware} stock-файли. Після перевірки вони будуть збережені у StockFirmware.",
    mcuBank1: "MCU Bank1",
    spiFlash: "SPI Flash",
    selectBackup: "Вибрати backup",
    buildFailed: "Помилка збірки",
    loadedGames: "Завантажені ігри",
    emulatorBuilder: "Емулятори",
    warning: "Попередження",
    liveLog: "Лог",
    flashDevice: "Прошити консоль",
    backupManager: "Менеджер backup",
    deviceStatus: "Статус консолі",
    programmer: "Програматор",
    deviceUid: "Device UID",
    voltage: "Напруга",
    detectedFirmware: "Визначена прошивка",
    externalFlash: "Зовнішня flash",
    protection: "Захист",
    gameStorage: "Сховище ігор",
    readingDeviceInfo: "Читання інформації...",
    readDeviceInfo: "Прочитати консоль",
    deviceReadFailedHint: "Пристрій не визначився. Перевірте підключення ST-LINK і живлення консолі, натисніть кнопку живлення на консолі та повторіть Read Device Info.",
    noWarnings: "Немає попереджень",
    systemOk: "Перевірку системи пройдено",
    languageUpdate: "Мова та оновлення програми",
    programUpdate: "Оновлення програми",
    probeFrequency: "Частота ST-LINK",
    probeFrequencyHint: "Старт з {khz} kHz, при помилках читання частота знижується автоматично",
    advancedFlasher: "Advanced Flasher",
    advancedFlasherHint: "Показати ручний backup і ручний запис прошивок",
    on: "Увімк",
    off: "Вимк",
    memoryUsage: "Використання памʼяті",
    builtSpiImage: "Зібраний SPI образ",
    overflow: "Переповнення",
    used: "Використано",
    emulatorRomsImage: "ROM / картинки емуляторів",
    builtExtflash: "Зібраний EXTFLASH",
    realSize: "Реальний розмір",
    runBuildFirmware: "Запустіть Build Firmware",
    readDeviceInfoMemory: "Прочитайте консоль, щоб показати SPI та використання памʼяті.",
    sdCard: "SD карта",
    backupShort: "BACKUP",
    fullBackupReady: "Backup збережено під UID консолі",
    readOrSelectBackup: "Зберігає прошивку під UID консолі",
    buildEmulator: "Зібрати емулятор",
    configureEmulatorCores: "Налаштувати ядра емуляторів",
    openEmulatorConfig: "Відкрити налаштування емуляторів",
    recoveryRestoreMode: "Режим відновлення",
    writeFirmwareToDevice: "Записати прошивку в консоль",
    nameAZ: "Імʼя A-Z",
    nameZA: "Імʼя Z-A",
    sizeUp: "Розмір ↑",
    sizeDown: "Розмір ↓",
    importImages: "Імпорт картинок",
    scanFolder: "Сканувати папку",
    clearRoms: "Очистити ROM",
    noGamesLoaded: "Ігри не завантажені",
    openRomFolder: "Відкрийте папку ROM для вибраного емулятора",
    addRomsAny: "Додайте ROM для будь-якого емулятора",
    unknownEmulator: "Невідомий емулятор",
    screenshotLoaded: "Скриншот завантажено",
    downloadingImage: "Завантаження картинки...",
    noScreenshotFound: "Скриншот не знайдено",
    noImage: "Немає картинки",
    setImage: "Вибрати картинку",
    setImageManual: "Вибрати картинку вручну",
    removeFromList: "Видалити зі списку",
    clear: "Очистити",
    firmwareRecovery: "Відновлення прошивки",
    firmwareRecoveryTitle: "Консоль перестала вмикатися або прошивка пошкоджена?",
    firmwareRecoveryText: "Процесор і UID читаються, але stock firmware не визначається. GW Studio спробує знайти backup для UID {uid} і підготувати відновлення у Flash Device. Якщо backup не знайдено, потрібно вибрати Bank1 і SPI файли вручну.",
    yesRecover: "Так, відновити",
    findBackupOrManual: "Знайти backup або вибрати файли вручну",
    no: "Ні",
    leaveBlocked: "Залишити операції заблокованими",
    restoreOriginalFirmware: "Відновити оригінальну прошивку",
    selectHardwareModel: "Виберіть реальну модель консолі",
    restoreOriginalHint: "M Hardware потрібно відновлювати stock-профілем M, Z Hardware — stock-профілем Z. Не використовуйте це для перетворення однієї моделі консолі на іншу.",
    marioHardware: "M Hardware",
    zeldaHardware: "Z Hardware",
    cancel: "Скасувати",
    msxBiosRequired: "Потрібен MSX BIOS",
    msxBiosHint: "У збірці є MSX ігри. Перетягніть сюди всі MSX BIOS файли, програма збереже їх поруч з exe у папку msx_bios і автоматично повторить Build Firmware.",
    colecoBiosRequired: "Потрібен ColecoVision BIOS",
    colecoBiosHint: "У збірці є ігри ColecoVision. Перетягніть файл coleco.rom вручну. Програма перевірить розмір 8192 байти та SHA-1, збереже BIOS поруч з exe у папку coleco_bios і повторить Build Firmware.",
    missingBios: "Не вистачає BIOS",
    checking: "Перевірка...",
    autoFlash: "Прошити збірку",
    autoFlashConfirm: "Ви впевнені? Буде виконано прошивку Bank1 + Bank2 + SPI.",
    flashBuildTitle: "Прошити збірку",
    flashBuildConfirm: "Ви впевнені? Буде прошито поточну збірку: Bank1 + Bank2 + SPI.",
    flashBuildButton: "Прошити збірку",
    autoFlashRunning: "Прошивка збірки...",
    autoFlashDone: "Прошивку завершено",
    autoFlashDoneHint: "Готово: Bank1 + Bank2 + SPI записано",
    writingBankSpi: "Запис Bank1 + Bank2 + SPI",
    buildFirmwareFirst: "Спочатку зберіть прошивку",
    firmwareBuiltReady: "Прошивку зібрано, можна прошивати",
    flashStockForkSpi: "Записати stock Bank1 + Bank2 fork + SPI",
    flashRetroGoOnly: "Записати Retro-Go Bank1 + SPI",
    writingSingleFirmware: "Запис Retro-Go Bank1 + SPI",
    singleFirmwareFlashConfirm: "Буде записано single firmware для hardware {hardware}: {targets}. Stock firmware і dual boot буде видалено.",
    bank1Missing: "Не знайдено Bank1 dualboot firmware",
    bank2Missing: "Не знайдено Bank2 fork firmware",
    restoreDevice: "Відновити прошивку",
    restoreDeviceConfirm: "Ви точно хочете відновити прошивку з backup, привʼязаного до UID {uid}?",
    unbrickDevice: "Unbrick Device",
    unbrickRunning: "Unbrick Device...",
    restoreDeviceRunning: "Відновлення прошивки...",
    installRecoveryFiles: "Запис stock firmware / recovery файлів",
    restoreSavedBackup: "Відновлення з backup за UID",
    installSelectedRecovery: "Записати вибрані stock Bank1 + SPI",
    selectRecoveryFirst: "Спочатку виберіть Bank1 і SPI recovery файли",
    restoreMcuSpiBackup: "Відновити MCU + SPI з backup за UID",
    readOrSelectMcuSpi: "Спочатку прочитайте консоль або виберіть MCU + SPI backup",
    restoreOriginalRunning: "Restore Original...",
    chooseHardwareThenFlash: "Виберіть M/Z Hardware, потім буде записаний stock",
    advancedFlash: "Advanced Flash",
    bank1Firmware: "Bank1 Firmware",
    bank2Firmware: "Bank2 Firmware",
    spiFirmware: "SPI Firmware",
    selectBank1Firmware: "Виберіть Bank1 firmware file",
    resolvedBank2Payload: "Знайдений Bank2 payload",
    selectSpiFirmware: "Виберіть SPI firmware file",
    writeBank1: "Write Bank1",
    writeBank2: "Write Bank2",
    writeSpiFlash: "Write SPI Flash",
    writeSelectedBank1: "Записати вибраний Bank1 firmware",
    writeBank2Payload: "Записати Bank2 payload у 0x08100000",
    writeSelectedSpi: "Записати вибраний SPI firmware",
    checkingSpiSectors: "Перевірка змінених SPI секторів...",
    prepareSpiFlash: "Підготовка SPI Flash",
    eraseSpiFlash: "Очищення SPI Flash",
    verifySpiFlash: "Перевірка SPI Flash",
    writeSpiFlashProgress: "Запис SPI Flash",
    writeBank1Progress: "Запис Bank1",
    writeBank2Progress: "Запис Bank2",
    verifyingSpi: "Перевірка записаної SPI flash...",
    erasingSpi: "Очищення зовнішньої SPI flash...",
    writingFirmware: "Запис прошивки...",
    readingFromDevice: "Читання з консолі",
    backup: "Backup",
    bank1Backup: "Bank1 Backup",
    bank2Backup: "Bank2 Backup",
    spiBackup: "SPI Backup",
    backupAppearsAfterSave: "Файл backup зʼявиться в /backups після збереження",
    advancedBackupAppearsAfterSave: "Advanced backup зʼявиться після збереження",
    lockedBankReadUnavailable: "LOCKED: читання Bank недоступне",
    readBank1: "Read Bank1",
    readBank2: "Read Bank2",
    readSpiFlash: "Read SPI Flash",
    readingBank1: "Reading Bank1...",
    readingBank2: "Reading Bank2...",
    readingSpi: "Reading SPI...",
    readBank1Backup: "Прочитати Bank1 backup з консолі",
    readBank2Backup: "Прочитати Bank2 backup з консолі",
    readSpiBackup: "Прочитати SPI flash backup з консолі",
    showInExplorer: "Показати в Explorer",
    runningAutoBackup: "Running Auto Backup...",
    autoBackupFinished: "Auto backup завершено",
    autoBackup: "Auto Backup",
    readSpiLocked: "Прочитати SPI backup з locked консолі",
    readFullBackup: "Зберігає Bank1 + Bank2 + SPI backup під UID консолі",
    advancedBackup: "Advanced Backup",
  },
};

export const EMULATORS = [
  ["nes", "NES", "/emulators/nes.png", "8-bit console"],
  ["gb", "GB", "/emulators/gb.png", "Game Boy"],
  ["gbc", "GBC", "/emulators/gbc.png", "Game Boy Color"],
  ["sms", "SMS", "/emulators/sms.png", "Sega Master System"],
  ["gg", "GG", "/emulators/gg.png", "Game Gear"],
  ["pce", "PCE", "/emulators/pce.png", "PC Engine"],
  ["col", "COL", "/emulators/col.png", "ColecoVision"],
  ["gw", "G&W", "/emulators/gw.png", "Game & Watch"],
  ["md", "MD", "/emulators/md.png", "Sega Genesis / Mega Drive"],
  ["sg", "SG-1000", "/emulators/sg.png", "Sega SG-1000"],
  ["msx", "MSX", "/emulators/msx.png", "MSX"],
  ["wsv", "WSV", "/emulators/wsv.png", "Watara Supervision"],
  ["a7800", "A7800", "/emulators/a7800.png", "Atari 7800"],
  ["tama", "Tama", "/emulators/tama.png", "Tamagotchi"],
];

export const EMULATOR_FILE_ACCEPT = {
  nes: ".nes,.fds,.nsf,.zip,.7z",
  gb: ".gb,.zip,.7z",
  gbc: ".gbc,.zip,.7z",
  sms: ".sms,.zip,.7z",
  gg: ".gg,.zip,.7z",
  pce: ".pce,.zip,.7z",
  col: ".col,.zip,.7z",
  gw: ".gw,.zip,.7z",
  md: ".md,.bin,.gen,.zip,.7z",
  sg: ".sg,.zip,.7z",
  msx: ".rom,.mx1,.mx2,.dsk,.zip,.7z",
  wsv: ".sv,.bin,.zip,.7z",
  a7800: ".a78,.bin,.zip,.7z",
  tama: ".b,.zip,.7z",
};

export function buildMockDeviceInfo() {
  return {
    programmer: "ST-LINK V3",
    probe_vendor: "STMicroelectronics",
    probe_id: "STLINK-V3MINI",
    mcu_profile: "STM32H7B3",
    detected_firmware: "Retro-Go fork",
    external_flash: "64 MB",
    protection: "LOCKED",
    filesystem: "READY",
    summary: "Mock runtime: Rust toolchain not built yet",
  };
}
